# Generated by Django 3.2 on 2021-05-02 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(max_length=15, verbose_name='شماره همراه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات')),
                ('payed', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('createDate', models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 38, 44, 705203), verbose_name='تاریخ ایجاد')),
                ('paymentDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('rrn', models.CharField(blank=True, max_length=250, null=True, verbose_name='RRN')),
                ('refId', models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره پیگیری')),
                ('resId', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه پرداخت')),
                ('cardNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت')),
            ],
            options={
                'verbose_name': 'پرداخت ها',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
