# Generated by Django 3.2 on 2021-05-02 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_auto_20210502_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 54, 17, 432514), verbose_name='تاریخ ایجاد'),
        ),
    ]
